apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
